# Generated by Django 2.2.9 on 2020-03-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_icon_id', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('puuid', models.CharField(max_length=78)),
                ('summoner_level', models.IntegerField()),
                ('revision_date', models.IntegerField()),
                ('summoner_id', models.CharField(max_length=63)),
                ('account_id', models.CharField(max_length=56)),
            ],
        ),
    ]
