# Generated by Django 2.2.9 on 2020-03-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='profile_icon_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='revision_date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summoner_level',
            field=models.BigIntegerField(),
        ),
    ]
