version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"

  web:
    # specifies path to build context (Dockerfile in top-level directory)
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit
 